// Genesis-free C++ port of the F1TENTH observation pipeline.
//
// Reproduces ros2_deploy/f1tenth_rl_agent/f1tenth_rl_agent/obs_core.py (which is in
// turn numerically identical to the training f1tenth_env/observations.py) for the
// single-vehicle (batch = 1) deploy case. A gtest parity suite compares this against
// fixtures generated by the Python pipeline (test/obs_fixture.txt).
//
// Standard library only (no Eigen / torch) to keep the on-car build lean.
#ifndef F1TENTH_RL_VEHICLE_RL_OBS_CORE_HPP_
#define F1TENTH_RL_VEHICLE_RL_OBS_CORE_HPP_

#include <array>
#include <string>
#include <vector>

namespace f1tenth_rl_vehicle
{

// Observation assembly parameters. Defaults match config.py DEFAULT_CONFIG["obs"]
// after the training/deploy parity alignment (scales 1.0, loose clip 50).
struct ObsConfig
{
  int num_obs = 380;
  int future_track_num_points = 60;
  double future_track_horizon_s = 6.0;
  double future_track_width = 2.2;
  double contact_margin_m = 0.08;
  double clip_obs = 50.0;
  double lin_vel_scale = 1.0;
  double ang_vel_scale = 1.0;
  double lin_acc_scale = 1.0;
};

// Current ego state in the track (map) frame. Velocities/accelerations are in the
// body frame, matching the training observation. tyre_slip is [slip_ratio x4,
// slip_angle x4]; deploy without per-wheel sensing passes zeros (gym parity).
struct VehicleState
{
  double pos_x = 0.0;
  double pos_y = 0.0;
  double yaw = 0.0;
  double vx = 0.0;
  double vy = 0.0;
  double wz = 0.0;
  double ax = 0.0;
  double ay = 0.0;
  double last_throttle = 0.0;
  double last_steer = 0.0;
  std::array<double, 8> tyre_slip{};
};

// Result of projecting a point onto the (closed) centerline.
struct FrenetState
{
  int best_idx = 0;
  double best_t = 0.0;
  double s = 0.0;   // arc length along the closed loop
  double L = 0.0;   // total closed-loop length
  double proj_x = 0.0;
  double proj_y = 0.0;
  double dir_x = 1.0;
  double dir_y = 0.0;
};

struct TrackData
{
  std::vector<double> x;
  std::vector<double> y;
  std::vector<double> w_left;
  std::vector<double> w_right;
};

// Parse a centerline CSV with columns x_m, y_m, w_tr_right_m, w_tr_left_m. Mirrors
// track_io.load_track_csv. Throws std::runtime_error on missing columns / parse
// failure.
TrackData loadTrackCsv(const std::string & path);

// Per-wheel slip [slip_ratio x4, slip_angle x4]; port of f1tenth_env/car.py
// compute_tyre_slip. Wheel order [LR, RR, LF, RF].
std::array<double, 8> computeTyreSlip(
  const std::array<double, 4> & v_fwd,
  const std::array<double, 4> & v_lat,
  const std::array<double, 4> & spin_rate,
  double wheel_radius,
  double slip_eps = 0.1);

// Map a policy action to (speed_mps, steering_angle_rad). Port of
// drive_math.map_action_to_drive. brake_behavior is "stop" or "reverse".
std::pair<double, double> mapActionToDrive(
  double throttle,
  double steering,
  double max_speed,
  double max_steer,
  double clip_actions = 1.0,
  const std::string & brake_behavior = "stop");

// Owns the track geometry and builds the 380-dim observation each control step.
class TrackObservationBuilder
{
public:
  TrackObservationBuilder(
    const std::vector<double> & xs,
    const std::vector<double> & ys,
    const std::vector<double> & w_left,
    const std::vector<double> & w_right,
    const ObsConfig & cfg,
    int coarse_stride = 10,
    int window = 40);

  // Assemble the observation. Returns a vector of length cfg.num_obs (float to
  // match the Float32MultiArray wire format). Throws if the assembled size differs.
  std::vector<float> build(const VehicleState & state) const;

  // Frenet projection of an arbitrary point (exposed for diagnostics / tests).
  FrenetState project(double px, double py) const;

  int numCenterlinePoints() const { return n_; }

private:
  ObsConfig cfg_;
  int coarse_stride_;
  int window_;

  // Closed-loop cache (used by Frenet projection): segment starts C, segment
  // vectors, segment lengths, cumulative arc length, total length L, count M.
  std::vector<double> cx_, cy_;
  std::vector<double> seg_x_, seg_y_, seg_len_, cumlen_;
  double total_len_ = 0.0;
  int m_ = 0;
  std::vector<int> coarse_idx_;

  // Track widths (length of the original centerline).
  std::vector<double> wl_, wr_;
  int nw_ = 0;

  // Open-polyline cache (used by the future-track points): original centerline,
  // its segment lengths and cumulative arc length.
  std::vector<double> ox_, oy_;
  std::vector<double> oseg_len_, ocumlen_;
  int n_ = 0;
};

}  // namespace f1tenth_rl_vehicle

#endif  // F1TENTH_RL_VEHICLE_RL_OBS_CORE_HPP_
