// Parity tests for rl_obs_core against fixtures generated by the Python pipeline.
//
// obs_fixture.txt is produced by gen_obs_fixture.py from the deployed Python
// ObservationBuilder, which the f1tenth_rl_agent parity test pins to the training
// f1tenth_env observation math. Passing here means the C++ observation equals the
// one the policy trained on (within float tolerance).
#include <array>
#include <cmath>
#include <fstream>
#include <string>
#include <vector>

#include "gtest/gtest.h"

#include "f1tenth_rl_vehicle/rl_obs_core.hpp"

using f1tenth_rl_vehicle::ObsConfig;
using f1tenth_rl_vehicle::TrackObservationBuilder;
using f1tenth_rl_vehicle::VehicleState;

namespace
{
std::string fixturePath()
{
  // Set by CMake (ament_add_gtest gets the source dir via a compile definition).
#ifdef OBS_FIXTURE_PATH
  return OBS_FIXTURE_PATH;
#else
  return "obs_fixture.txt";
#endif
}
}  // namespace

TEST(RlObsCore, MatchesPythonFixture)
{
  std::ifstream f(fixturePath());
  ASSERT_TRUE(f.is_open()) << "cannot open fixture: " << fixturePath();

  int n = 0;
  f >> n;
  ASSERT_GT(n, 1);
  std::vector<double> xs(n), ys(n), wl(n), wr(n);
  for (int i = 0; i < n; ++i) {
    f >> xs[i] >> ys[i] >> wl[i] >> wr[i];
  }

  ObsConfig cfg;
  double samples, horizon, width, contact, clip, sv, sa, sc;
  f >> samples >> horizon >> width >> contact >> clip >> sv >> sa >> sc;
  cfg.num_obs = 380;
  cfg.future_track_num_points = static_cast<int>(samples);
  cfg.future_track_horizon_s = horizon;
  cfg.future_track_width = width;
  cfg.contact_margin_m = contact;
  cfg.clip_obs = clip;
  cfg.lin_vel_scale = sv;
  cfg.ang_vel_scale = sa;
  cfg.lin_acc_scale = sc;

  TrackObservationBuilder builder(xs, ys, wl, wr, cfg);

  int num_cases = 0;
  f >> num_cases;
  ASSERT_GT(num_cases, 0);

  double max_diff = 0.0;
  for (int c = 0; c < num_cases; ++c) {
    VehicleState st;
    f >> st.pos_x >> st.pos_y >> st.yaw >> st.vx >> st.vy >> st.wz >> st.ax >> st.ay >>
    st.last_throttle >> st.last_steer;
    for (int i = 0; i < 8; ++i) {
      f >> st.tyre_slip[i];
    }
    std::vector<double> expected(cfg.num_obs);
    for (int i = 0; i < cfg.num_obs; ++i) {
      f >> expected[i];
    }

    std::vector<float> obs = builder.build(st);
    ASSERT_EQ(static_cast<int>(obs.size()), cfg.num_obs);
    for (int i = 0; i < cfg.num_obs; ++i) {
      double d = std::abs(static_cast<double>(obs[i]) - expected[i]);
      max_diff = std::max(max_diff, d);
      EXPECT_LT(d, 1e-4) << "case " << c << " index " << i
                         << " got " << obs[i] << " expected " << expected[i];
    }
  }
  EXPECT_LT(max_diff, 1e-4) << "max obs parity diff = " << max_diff;
}

TEST(RlObsCore, TyreSlipMatchesFormula)
{
  // Straight-rolling wheel: spin_rate * radius == v_fwd -> zero slip ratio,
  // zero lateral velocity -> zero slip angle.
  std::array<double, 4> v_fwd{2.0, 2.0, 2.0, 2.0};
  std::array<double, 4> v_lat{0.0, 0.0, 0.0, 0.0};
  std::array<double, 4> spin{40.0, 40.0, 40.0, 40.0};  // 40 rad/s * 0.05 m = 2 m/s
  auto slip = f1tenth_rl_vehicle::computeTyreSlip(v_fwd, v_lat, spin, 0.05, 0.1);
  for (int i = 0; i < 8; ++i) {
    EXPECT_NEAR(slip[i], 0.0, 1e-9);
  }

  // Locked wheel (spin 0) while moving forward -> slip_ratio = -v_fwd/max(|v|,eps).
  std::array<double, 4> spin0{0.0, 0.0, 0.0, 0.0};
  auto slip2 = f1tenth_rl_vehicle::computeTyreSlip(v_fwd, v_lat, spin0, 0.05, 0.1);
  for (int i = 0; i < 4; ++i) {
    EXPECT_NEAR(slip2[i], -1.0, 1e-9);  // (0 - 2) / max(0, 2) = -1
  }
}

TEST(RlObsCore, MapActionToDrive)
{
  auto [speed, steer] =
    f1tenth_rl_vehicle::mapActionToDrive(0.5, -0.5, 15.0, 0.44, 1.0, "stop");
  EXPECT_NEAR(speed, 7.5, 1e-9);
  EXPECT_NEAR(steer, -0.22, 1e-9);

  // brake_behavior "stop": negative throttle -> zero speed.
  auto [speed_stop, steer_stop] =
    f1tenth_rl_vehicle::mapActionToDrive(-0.5, 0.0, 15.0, 0.44, 1.0, "stop");
  EXPECT_NEAR(speed_stop, 0.0, 1e-9);
  EXPECT_NEAR(steer_stop, 0.0, 1e-9);

  // brake_behavior "reverse": negative throttle -> negative speed.
  auto [speed_rev, steer_rev] =
    f1tenth_rl_vehicle::mapActionToDrive(-0.5, 1.0, 15.0, 0.44, 1.0, "reverse");
  EXPECT_NEAR(speed_rev, -7.5, 1e-9);
  EXPECT_NEAR(steer_rev, 0.44, 1e-9);
}
